services:
  ollama-gpu:
    image: ollama/ollama
    container_name: ollama-gpu
    ports:
      - "11434:11434"
    environment:
      OLLAMA_NUM_PARALLEL: "2"
      # OLLAMA_GPU_OVERHEAD: "1073741824" # 1.25 GiB
      OLLAMA_GPU_OVERHEAD: "1073741824" # 1 GiB
      # OLLAMA_GPU_OVERHEAD: "1342177280" # 1.25 GiB
      # OLLAMA_GPU_OVERHEAD: "1610612736" # 1.5 GiB
      # OLLAMA_GPU_OVERHEAD: "1879048192" # 1.75 GiB
      # OLLAMA_GPU_OVERHEAD: "2147483648" # 2 GiB

    volumes:
      - type: bind
        source: D:\ollama\models
        target: /root/.ollama/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  ollama-cpu:
    image: ollama/ollama
    container_name: ollama-cpu
    ports:
      - "11435:11434"
    volumes:
      - type: bind
        source: D:\ollama\models
        target: /root/.ollama/models
    environment:
      OLLAMA_NUM_PARALLEL: "2"
      CUDA_VISIBLE_DEVICES: "-1"

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage

volumes:
  qdrant_storage:
